In [13]:
import pandas as pd

# Caminho para o CSV (ajuste se necessário)
caminho_csv = './resultados_ga.csv'

# Carregar o CSV em um DataFrame
df = pd.read_csv(caminho_csv)

# Visualizar as primeiras linhas
df.head(81)

,pop_size,geracoes,elite_rate,mutation_rate,melhor_solucao,melhor_custo,tempo_execucao_s
0,50,50,1,0.05,[5 4 6 8 9 7 2 3 1 0],5391.0,0.047483
1,50,50,1,0.10,[7 4 5 8 9 2 0 6 3 1],5802.0,0.021652
2,50,50,1,0.15,[5 2 6 0 1 4 7 9 3 8],5682.0,0.019812
3,50,50,2,0.05,[6 5 0 8 7 3 9 1 2 4],5317.0,0.019075
4,50,50,2,0.10,[9 2 0 8 7 3 4 1 6 5],5489.0,0.021231
...,...,...,...,...,...,...,...
76,150,200,2,0.10,[5 4 8 7 1 3 2 6 0 9],5476.0,0.083410
77,150,200,2,0.15,[7 4 5 8 3 6 0 1 2 9],5597.0,0.080066
78,150,200,4,0.05,[5 3 8 7 9 0 4 2 6 1],5794.0,0.104794
79,150,200,4,0.10,[8 1 6 0 5 7 9 2 3 4],5516.0,0.077916
80,150,200,4,0.15,[9 4 5 8 0 3 1 2 6 7],5696.0,0.080779

In [14]:
df.describe()

,pop_size,geracoes,elite_rate,mutation_rate,melhor_custo,tempo_execucao_s
count,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000
mean,100.000000,116.666667,2.333333,0.100000,5634.691358,0.048610
std,41.079192,62.749502,1.254990,0.041079,126.742617,0.021322
min,50.000000,50.000000,1.000000,0.050000,5317.000000,0.019075
25%,50.000000,50.000000,1.000000,0.050000,5564.000000,0.031948
50%,100.000000,100.000000,2.000000,0.100000,5647.000000,0.044639
75%,150.000000,200.000000,4.000000,0.150000,5715.000000,0.070905
max,150.000000,200.000000,4.000000,0.150000,5923.000000,0.104794